### ISSUE TITLE
Color scale error when making box plot

### ISSUE THREAD

**Issue by jswarts14** [CirroBioApps/mudata-explorer#10]
![Screenshot 2024-06-10 at 1 52 18 PM](https://github.com/CirroBioApps/mudata-explorer/assets/172069692/eff82a5a-079c-4eec-ab67-590ff17c8856)
![Screenshot 2024-06-10 at 1 55 58 PM](https://github.com/CirroBioApps/mudata-explorer/assets/172069692/d6d86751-46ae-485c-b1ba-22c6f06c195d)

**Comment by sminot** [comment]
For box plots, the color scale must always be categorical. This can be accomplished by clicking the "Categorical Values" box. I will make that option selection True by default so that this error doesn't come up for new plots. Thanks for the catch!
