### ISSUE TITLE
Attempting to upload Metadata in xlsx format and received error

### ISSUE THREAD

**Issue by jswarts14** [CirroBioApps/mudata-explorer#11]
![Screenshot 2024-06-24 at 11 40 06 AM](https://github.com/CirroBioApps/mudata-explorer/assets/172069692/d2c00ab7-45bb-4d97-9a60-e9cbf63e31cc)

**Comment by sminot** [comment]
The logs say "0 sheets found". Would you mind emailing me the file so that I can take a look?

**Comment by sminot** [comment]
It looks like you ran into this issue: https://stackoverflow.com/questions/69948897/pandas-valueerror-worksheet-index-0-is-invalid-0-worksheets-found

The file which caused the error was saved as "Strict Open XML Spreadsheet (*.xlsx)". If you resave as "Excel Workbook (*.xlsx)" instead, it should work.
