### ISSUE TITLE
Issue loading in observational metadata

### ISSUE THREAD

**Issue by fmaclean** [CirroBioApps/mudata-explorer#13]
Hi,

I am getting the following error when trying to load in metadata. Can you help? 

![Screenshot 2024-09-09 at 11 48 46 AM](https://github.com/user-attachments/assets/a965795d-90b3-485e-a668-a32978be1c1c)

Thanks!

**Comment by sminot** [comment]
Would you be able to provide an example dataset to reproduce the issue?

**Comment by sminot** [comment]
I appreciate your providing the example, @fmaclean. I was able to update the process to follow what the newest version of the mudata library expects, and I've confirmed that your example works on the updated app that is live now. Please do open another issue if you run into more issues!
