### ISSUE TITLE
Trouble with analyses

### ISSUE THREAD

**Issue by fmaclean** [CirroBioApps/mudata-explorer#14]
I am having trouble generating a PCA plot or UMAP with the data set as is. The error seems to be in reference to NA values in the data set. Is there a way to have the app ignore NA values?

Additionally, I tried running 'dbscan' but I am not sure if it ran correctly. I am having trouble locating the clusters and using them to visualize the data. On the tables tab, it generates but looks empty. 

![Screenshot 2024-09-09 at 1 45 08 PM](https://github.com/user-attachments/assets/eb41e9c7-31f3-4127-8042-c55ec23d0f21)
![Screenshot 2024-09-09 at 1 45 45 PM](https://github.com/user-attachments/assets/ecb3b8e6-db7b-4597-8d79-b00afad80ea9)
![Screenshot 2024-09-09 at 1 50 29 PM](https://github.com/user-attachments/assets/cd6218bb-a784-4328-a98a-6df25b774927)

Thanks

**Comment by sminot** [comment]
The DBSCAN issue is also probably related to the N/A's in the data.

In terms of dealing with them, do you have an idea of what value they should be interpreted as when there's a missing value? The algorithm uses information from every cell in the table, so we'd just have to fill in the right thing.

Another option is that you can just select the columns which don't have any N/A's for those samples. Might that help in this case?

**Comment by fmaclean** [comment]
Thanks for the tip! I got it to work with removing the null values. I am just now having trouble with graphing UMAP1 vs UMAP2. I can graph UMAP1 on its own with a different variable. I was able to graph a PCA plot as well. Any ideas? 

Thanks. 

![Screenshot 2024-09-09 at 3 47 03 PM](https://github.com/user-attachments/assets/c2ceb9a3-6a30-4706-87c4-8c7f90aa4a7b)

**Comment by sminot** [comment]
Can you send me the .h5mu file for the dataset that you're getting this error in?

**Comment by fmaclean** [comment]
I am having trouble finding the option to save as a .h5mu file in this version. I only see an option to save to cirro.

**Comment by sminot** [comment]
![image](https://github.com/user-attachments/assets/cb74b050-0dba-4237-a0f5-f33f38bbed54)

If you aren't seeing a page that looks like this, then it might be worth hopping on a quick call to debug together. Feel free to snag any time on my Outlook calendar that's open.

**Comment by fmaclean** [comment]
Will do

**Comment by sminot** [comment]
Should be resolved now
