### ISSUE TITLE
UMAP generation error

### ISSUE THREAD

**Issue by jswarts14** [CirroBioApps/mudata-explorer#8]
![Screenshot 2024-06-07 at 10 45 27 AM](https://github.com/CirroBioApps/mudata-explorer/assets/172069692/8a1256e1-da4a-4461-bef2-042ae143b9cf)
![Screenshot 2024-06-07 at 10 45 40 AM](https://github.com/CirroBioApps/mudata-explorer/assets/172069692/a2ed85d6-ae81-406e-bcea-7eaeb2255717)

I have the data saved that caused the error if needed

**Comment by sminot** [comment]
I've just pushed a pretty big change to how the input data is selected for analysis, which I think should resolve this. Please do open another issue if the updated interface does not work with the same data.

**Comment by jswarts14** [comment]
Yep, the problem was fixed when I used the same data just now.
